version: '3.1'
services:
  tern:
    build: ./
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - dbpostgresql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=polldb
      - POSTGRES_HOST=dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=polldb
      - POSTGRES_HOST=dbpostgresql