syntax = "proto3";
package tern.grpc;
import "google/protobuf/empty.proto";

message Message {
  string id = 1;
  string text = 2;
  // Empty when the detector was unavailable.
  string language = 3;
}

message GetResponse {
  repeated Message messages = 1;
}

message SaveRequest {
  string text = 1;
  string language = 2;
}

message SaveResponse {
  string id = 1;
}

message UpdateLanguageRequest {
  string id = 1;
  string language = 2;
}

service TernService {
  rpc GetMessage (google.protobuf.Empty) returns (GetResponse) {}
  rpc SaveMessage (SaveRequest) returns (SaveResponse);
  rpc UpdateLanguage (UpdateLanguageRequest) returns (google.protobuf.Empty);
}
