server:
  port: 8080
spring:
  flyway:
    baselineOnMigrate: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER} #postgres
    password: ${POSTGRES_PASSWORD} #password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none