apiVersion: apps/v1
kind: Deployment
metadata:
  name: artic
spec:
  selector:
    matchLabels:
      app: artic
  replicas: 1
  template:
    metadata:
      labels:
        app: artic
    spec:
      containers:
        - name: tern
          image: tern:23
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_password
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_host
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.5"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgres_user: postgres
  postgres_password: password
  postgres_host: postgresql

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: artic-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: artic
  minReplicas: 1
  maxReplicas: 1 # 10
  targetCPUUtilizationPercentage: 50

---
apiVersion: v1
kind: Service
metadata:
  name: artic
spec:
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app: artic
