apiVersion: batch/v1
kind: CronJob
metadata:
  name: curl-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl-cronjob
              image: tern:latest
              imagePullPolicy: Never
              command:
                - /bin/sh
                - -c
                - |
                  curl -X POST http://artic.default.svc.cluster.local:8080/ \
                    -H "Content-Type: application/json" \
                    -d '{"text": "some-text"}'
          restartPolicy: OnFailure
